# Generated by Django 5.1.7 on 2026-05-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("discount", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("expiry_date", models.DateField()),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
