# Generated by Django 5.1.7 on 2026-05-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0004_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery.deliverypartner",
            ),
        ),
    ]
